shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*
  - packages/parser/tree-sitter-jsrs
  - test
allowBuilds:
  core-js: true
  esbuild: true
  tree-sitter: true
  tree-sitter-cli: true
